---
- name: config | NSO customer configuration
  nso_config:
    url: "https://{{ ansible_host }}:8888/jsonrpc"
    username: "admin"
    password: "admin"
    validate_certs: false
    data:
      tailf-ncs:customers:
        customer: "{{ nso_customers }}"
  when: nso_customers is defined and nso_customers
