---
- name: config | NSO customer configuration
  nso_config:
    url: "http://{{ ansible_host }}:8080/jsonrpc"
    username: "admin"
    password: "admin"
    validate_certs: false
    data:
      tailf-ncs:customers:
        customer: "{{ nso_customers }}"
  delegate_to: localhost
  when: nso_customers is defined and nso_customers
