---
- name: install | Create NSO working directory
  file:
    path: "{{ nso_root_dir }}"
    state: directory
    mode: '0755'

- name: install | Copy NSO {{ nso_version }} signed binary to remote host
  copy:
    src: "{{ nso_signed_binary }}"
    dest: "{{ bin_working_dir }}"
    mode: '0755'
  when: ansible_host != "localhost"

- name: install | Unpack NSO {{ nso_version }} signed binary
  command: "sh {{ nso_signed_binary }} --skip-verification"
  args:
    chdir: "{{ bin_working_dir }}"
    creates: "{{ nso_install_binary }}"

- name: install | Run NSO {{ nso_version }} Local installation
  command: "sh {{ nso_install_binary }} --local-install {{ nso_install_dir }}"
  args:
    chdir: "{{ bin_working_dir }}"
    creates: "{{ nso_install_dir }}"

- name: install | Install external YANG files
  include: "yang-files.yml"
  when: nso_yang_files is defined and nso_yang_files
