---
# tasks file for ansible-nso-local-install
- name: main | Gather operating system variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - "always"

- name: main | Pre-flight
  include: "pre-flight.yml"
  tags:
    - "always"

- name: main | Install
  include: "install.yml"
  tags:
    - "always"

- name: main | Runtime
  include: "runtime.yml"
  tags:
    - "always"

- name: main | NED packages
  include: "neds.yml"
  when: nso_ned_signed_binaries is defined and nso_ned_signed_binaries
  tags:
    - "nso_neds"

- name: main | Flush handlers
  meta: flush_handlers
  tags:
    - "always"

- name: main | NETSIM devices
  include: "netsim.yml"
  when: nso_netsim is defined and nso_netsim
  tags:
    - "nso_netsim"

- name: main | Configuration
  include: "config.yml"
  tags:
    - "nso_config"

- name: main | Cleanup
  include: "cleanup.yml"
  tags:
    - "always"
