---
- name: neds | Unpack NED signed binaries
  command: "sh {{ item }}"
  args:
    chdir: "{{ role_path }}/files/neds"
    creates: "{{ item | regex_search('(.+[^.signed.bin])', '\\1') | first }}.tar.gz"
  loop: "{{ nso_ned_signed_binaries }}"

- name: neds | Unarchive NED packages into NSO {{ nso_version }} runtime
  unarchive:
    src: "{{ role_path }}/files/neds/{{ item | regex_search('(.+[^.signed.bin])', '\\1') | first }}.tar.gz"
    dest: "{{ nso_runtime_dir }}/packages"
  loop: "{{ nso_ned_signed_binaries }}"

- name: neds | Register NED packages from NSO {{ nso_version }} runtime
  find:
    paths: "{{ nso_runtime_dir }}/packages"
    file_type: directory
  register: nso_ned_dir

- name: neds | Compile NED packages
  shell: "source {{ nso_install_dir }}/ncsrc && make clean all --directory {{ item.path }}/src"
  args:
    executable: /bin/bash
  loop: "{{ nso_ned_dir.files }}"
