---
- name: neds | Copy NED signed binaries to remote host
  copy:
    src: "{{ item }}"
    dest: "{{ bin_working_dir }}"
    mode: '0755'
  loop: "{{ nso_ned_signed_binaries }}"
  when: ansible_host != "localhost"

- name: neds | Unpack NED signed binaries
  command: "sh {{ item }} --skip-verification"
  args:
    chdir: "{{ bin_working_dir }}"
    creates: "{{ item | regex_search('(.+[^.signed.bin])', '\\1') | first }}.tar.gz"
  loop: "{{ nso_ned_signed_binaries }}"

- name: neds | Unarchive NED packages into NSO {{ nso_version }} runtime
  unarchive:
    src: "{{ bin_working_dir }}/{{ item | regex_search('(.+[^.signed.bin])', '\\1') | first }}.tar.gz"
    dest: "{{ nso_runtime_dir }}/packages"
  loop: "{{ nso_ned_signed_binaries }}"
  when: ansible_host == "localhost"

- name: neds | Unarchive NED packages into NSO {{ nso_version }} runtime on remote host
  unarchive:
    src: "{{ bin_working_dir }}/{{ item | regex_search('(.+[^.signed.bin])', '\\1') | first }}.tar.gz"
    dest: "{{ nso_runtime_dir }}/packages"
    remote_src: true
  loop: "{{ nso_ned_signed_binaries }}"
  when: ansible_host != "localhost"

- name: neds | Register NED packages from NSO {{ nso_version }} runtime
  find:
    paths: "{{ nso_runtime_dir }}/packages"
    file_type: directory
  register: nso_ned_dir

- name: neds | Compile NED packages
  shell: "source {{ nso_install_dir }}/ncsrc && make clean all --directory {{ item.path }}/src"
  args:
    executable: /bin/bash
  loop: "{{ nso_ned_dir.files }}"
  notify: "reload nso packages"
