---
- name: runtime | Create NSO {{ nso_version }} runtime
  shell: "source {{ nso_install_dir }}/ncsrc && ncs-setup --dest {{ nso_runtime_dir }}"
  args:
    executable: /bin/bash
    creates: "{{ nso_runtime_dir }}"

- name: runtime | Register NSO {{ nso_version }} status
  shell: "source {{ nso_install_dir }}/ncsrc && ncs --status"
  args:
    executable: /bin/bash
  register: ncs_status
  ignore_errors: true
  no_log: true

- name: runtime | Start NSO {{ nso_version }}
  shell: "cd {{ nso_runtime_dir }} && source {{ nso_install_dir }}/ncsrc && ncs --with-package-reload"
  args:
    executable: /bin/bash
  when: ncs_status.rc > 0

- name: runtime | Create NSO {{ nso_version }} runtime configuration
  template:
    src: "local.ncs.conf.j2"
    dest: "{{ nso_runtime_dir }}/ncs.conf"
    mode: 0664
  notify: "reload nso runtime config"
