---
nso_root_dir: "~/nso"
nso_yang_files:
  - name: "ietf-routing-types.yang"
    uri: "https://raw.githubusercontent.com/YangModels/yang/master/standard/ietf/RFC/ietf-routing-types%402017-12-04.yang"
nso_netsim:
  - type: iosxr
    type_count: 3
    type_count_gige: 2
    type_count_tengige: 2
  - type: ios
    type_count: 3
    type_count_gige: 2
    type_count_tengige: 2
